### PR TITLE
Fixes yogbot bug reports round id

### PR DESCRIPTION
**Pull request by TheGamerdk**
oops

### CODE REVIEW

**Review by adamsong — APPROVED** [review]

**Review by alexkar598 — CHANGES_REQUESTED** [review]
No. Set it to null by default

**Comment by adamsong** [comment]
> No. Set it to null by default

You sure about that? https://github.com/yogstation13/yogbot/pull/342/files#diff-55c40a04b6b877d2ee35c558e26e6cde3e3a8f7aa8f05c56e69de4e733ba261aL25

**Comment by alexkar598** [comment]
"Set it to null by default"
It's not null by default, make it that way, or an empty string to remain consistent with the rest of the vars

**Review by alexkar598 — APPROVED** [review]

**Comment by adamsong** [comment]
> "Set it to null by default"

Reading is hard, you can't make me

**Pull request merged**
