### PR TITLE
Revert "[s] Adds a classic dad joke"

### PR DESCRIPTION
**Pull request by ThatLing**
Reverts yogstation13/yogbot#114

### CODE REVIEW

**Comment by Ktlwjec** [comment]
please hurry

**Comment by nichlas0010** [comment]
good thing we need @AshCorr to merge yogbot stuff, instead of just having it be integrated into the main repo and ahving headcoders preside over it :^)

**Comment by Kmc2000** [comment]
Do not merge

**Comment by thehighwayman** [comment]
do merge

**Comment by nichlas0010** [comment]
why do staff even have the ability to open&close PRs

**Comment by thehighwayman** [comment]
because you invited them all to the organization and gave them the ability :thinking:

**Pull request merged**
