### PR TITLE
Revert "I hope you're prepared for an unforgettable luncheon."

### PR DESCRIPTION
**Pull request by LoliconSlayer**
Reverts yogstation13/yogbot#311

Not explicitly mentor related

### CODE REVIEW

**Comment by maxion12345** [comment]
> Reverts #311
> 
> Not explicitly mentor related

someone was not prepared for the unforgettable luncheon

**Comment by Cartlord** [comment]
i agree, i don't see how it's a Mentor Moment(TM)

**Comment by Tipy1802** [comment]
Isn't Tim Clark a mentor?

**Comment by TheLinuxOS** [comment]
> Isn't Tim Clark a mentor?

Yes

**Comment by Hopekz** [comment]
> i agree, i don't see how it's a Mentor Moment(TM)

I think like 40% of all images in the command don't really have to do with something mentor-related.
I think it evolved to just "funny or cool moments that a mentor was involved in" but some of the screenshots in there are mine and I wasn't really directly a mentor so I don't really know.

**Comment by alexkar598** [comment]
idk the votes say 3 to 1 and i dont have any strong opinion either way to justify going against the vote.

and noone else did anything to this pr  sooo

**Pull request closed without merging**
