### PR TITLE
fixes spam

### PR DESCRIPTION
**Pull request by nichlas0010**

### CODE REVIEW

**Comment by Nickvr628** [comment]
closed for not having changelog

**Comment by nichlas0010** [comment]
I'd like you to look at every single other PR in this repo. None of them have changelogs

**Comment by Nickvr628** [comment]
then close them all

**Comment by nichlas0010** [comment]
or I could close your comments

**Comment by nichlas0010** [comment]
are you seriously upvoting your own comments...

**Comment by AshCorr** [comment]
I like this PR

**Pull request closed without merging**
