### PR TITLE
allows [s] to stop PRs from being posted on discord

### PR DESCRIPTION
**Pull request by nichlas0010**

### CODE REVIEW

**Comment by 1fbff5f83b23d39d38b1dfcb4cac8d9b** [comment]
I'd use startsWith() instead of includes() but it's prolly no big deal

**Comment by nichlas0010** [comment]
Just in case someone puts it at the end or smthn

**Comment by AshCorr** [comment]
> selfmerge

🤔

**Comment by nichlas0010** [comment]
>better than no merge
🤔 
image

**Comment by AshCorr** [comment]
> 🤔

Its being reviewed 1 line per day ofc, need to make sure every line is perfect!

**Comment by nichlas0010** [comment]
image
🤔

**Pull request merged**
